### ISSUE TITLE
NoSuchElementException: No value present in InverseDepsAnalyzer

### ISSUE THREAD

**Issue by FrankRuben** [SAP/SapMachine#1037]
Hi,
not sure whether I need to create an issue here or in OpenJDK, but since I'm running into the issue with SapMachine I figure I might as well enter it here.

I'm trying to check our (non-public (but SAP-internal)) repo using `jdeps` and I'm getting the following error:

```
> jdeps.exe -version
19-ea 
# Note: same for version 17

> jdeps.exe --multi-release 11 --module-path . --inverse --package {some-package-name} {some-jar}.jar

Inverse transitive dependences matching packages [{some-package-name}]
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143)
        at jdk.jdeps/com.sun.tools.jdeps.InverseDepsAnalyzer.lambda$inverseDependences$2(InverseDepsAnalyzer.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at jdk.jdeps/com.sun.tools.jdeps.InverseDepsAnalyzer.lambda$inverseDependences$3(InverseDepsAnalyzer.java:150)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
        at jdk.jdeps/com.sun.tools.jdeps.InverseDepsAnalyzer.inverseDependences(InverseDepsAnalyzer.java:145)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask$InverseAnalyzeDeps.run(JdepsTask.java:861)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:575)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:534)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```

**Comment by RealCLanger** [comment]
Hi @FrankRuben,

thanks for reporting this error. Do you have a standalone repro case? If you say your repository is sap-internal, you can also contact me internally and we can have a look together.

Cheers
Christoph

**Comment by RealCLanger** [comment]
I'm closing this issue. But feel free to contact me, should the problem still persist. Either directly or via commenting here.

**Comment by FrankRuben** [comment]
_Update_: further communication via email

**Comment by RealCLanger** [comment]
Created: https://bugs.openjdk.org/browse/JDK-8293701
