### ISSUE TITLE
Facing Null pointer exception in the OOB application when a cronjob runs - Could be related to java version

### ISSUE THREAD

**Issue by imanuel-sammeta** [SAP/SapMachine#1849]
Please see the log below.

Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null             at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)             at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)             at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)            at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)             at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:358)             at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:315)             at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)             at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:315)             at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)             at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)             ... 30 more

**Comment by RealCLanger** [comment]
Hi @imanuel-sammeta ,

can you please provide more details about this error, e.g. a reproducer and information about your system environment.

Also, are you using SapMachine or another JDK distribution? Are you using this in an SAP context, e.g. are you an SAP internal or have an SAP customer number to file an official support ticket with SAP?

Thanks
Christoph

**Comment by RealCLanger** [comment]
Closing the issue due to no response. However, feel free to add additional comments.
